[project]
name = "think-stats"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
  "ipykernel>=7.1.0",
  "ipython>=9.10.0",
  "jupytext>=1.19.1",
  "lxml>=6.0.2",
  "matplotlib>=3.10.8",
  "nbconvert>=7.17.0",
  "numpy>=2.4.2",
  "pandas>=3.0.0",
  "pandas-stubs>=3.0.0.260204",
  "scikit-learn>=1.8.0",
  "scipy-stubs>=1.17.0.2",
  "seaborn>=0.13.2",
  "statadict>=1.1.0",
  "statsmodels>=0.14.6",
  "tables>=3.10.2",
]

[dependency-groups]
dev = ["pyqt6>=6.10.2"]

[tool.basedpyright]
exclude = ["**/__pycache__", ".venv"]
# reportAny = false
# reportUnknownArgumentType = false
# reportUnknownLambdaType = false
# reportUnknownMemberType = false
# reportUnknownVariableType = false
reportUnusedCallResult = false
reportUnusedExpression = false
reportUnusedVariable = false
reportArgumentType = false
typeCheckingMode = "basic"
